# @TODO: Update project to node v20 since node v16 is deprecated: https://nodejs.org/en/blog/announcements/nodejs16-eol
# @TODO: Improve pipeline for deployment: https://github.com/spalladino/sample-contract-deploy-pipeline
# @TODO: Foundry test coverage: https://www.rareskills.io/post/foundry-forge-coverage
# @TODO: Hardhat coverage: https://hardhat.org/hardhat-runner/docs/guides/test-contracts#measuring-code-coverage
name: bloc/QA/hardhat
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging
      - "!releases/**"

defaults:
  run:
    shell: bash
    working-directory: bloc

jobs:
  # Testing hardhat
  test_hardhat_tests:
    name: Hardhat tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run typescript tests (hardhat)
        run: npm ci && npx hardhat test

  # Testing hardhat script deployment
  test_hardhat_deployment:
    name: Hardhat deployment
    runs-on: ubuntu-latest
    needs: test_hardhat_tests
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Deployment with hardhat
        run: npm ci && npx hardhat run scripts/template/Box/deployBox.ts --network hardhat
